### ISSUE TITLE
Nest channel stops after a connection error

### ISSUE THREAD

**Issue by eigenein** [eigenein/iftttie#35]
- The channel doesn't restart automatically
- The error description is missing, whilst supposed to be there
- Perhaps not related to this specific channel, should be a bug in the core

```
Jan 25 23:14:01 (iftttie.channels.nest:36) [E] Connection error:
Jan 25 23:14:01 (iftttie.core:28) [I] Stopped channel Nest(token="c.Am…xoGd").
```

**Comment by eigenein** [comment]
Backtrace is fixed. It's only unclear why it exits the loop as a cancelled one.

```python
Jan 26 15:08:49 (iftttie.channels.nest:36) [E] Connection error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/iftttie/channels/nest.py", line 31, in run
    async for server_event in source:
  File "/usr/local/lib/python3.7/site-packages/aiohttp_sse_client/client.py", line 145, in __anext__
    async for line_in_bytes in self._response.content:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 32, in __anext__
    rv = await self.read_func()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 292, in readline
    await self._wait('readline')
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 259, in _wait
    with self._timer:
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 663, in __enter__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Jan 26 15:08:49 (iftttie.core:28) [I] Stopped channel Nest(token="c.Am…xoGd").
```

**Comment by eigenein** [comment]
```
Jan 26 19:13:56 (iftttie.channels.nest:28) [I] Connecting to the streaming API…
Jan 26 19:13:56 (iftttie.core:28) [I] Stopped channel Nest(token="c.Am…xoGd").
```

**Comment by eigenein** [comment]
It gets cancelled at the retry:

```python
            logger.info('Connecting to the streaming API…')
            async with EventSource(url, params=self.params, headers=headers, session=context.session) as source:
```

```python
        try:
            await channel.run(app.context)
        except CancelledError:
            logger.info('Stopped channel {channel}.', channel=channel)
```

**Comment by eigenein** [comment]
Confirmed, ac672ec fixes it.

**Comment by eigenein** [comment]
```text
Jan 27 17:37:50 (iftttie.channels.nest:39) [W] Connection timeout.
Jan 27 17:37:50 (iftttie.channels.nest:31) [I] Connecting to the streaming API…
Jan 27 17:37:51 (iftttie.channels.nest:33) [I] Connected.
Jan 27 17:37:51 (iftttie.context:50) [I] nest:structure:NFoW367Rt9Srr_hg0Pvi01Fb7R0JazU2pZp9To64fE8FExvo0FoJRA:away = 'home'
Jan 27 17:37:51 (iftttie.context:50) [I] nest:structure:NFoW367Rt9Srr_hg0Pvi01Fb7R0JazU2pZp9To64fE8FExvo0FoJRA:wwn_security_state = 'ok'
Jan 27 17:37:51 (iftttie.context:50) [I] nest:camera:q3x00MXx02yD67celwVrWGYhDcPZHDmmCn_-2slU1zZtYZY1MsHG6w:is_streaming = True
--
Jan 27 17:47:51 (iftttie.channels.nest:39) [W] Connection timeout.
Jan 27 17:47:51 (iftttie.channels.nest:31) [I] Connecting to the streaming API…
Jan 27 17:47:52 (iftttie.channels.nest:33) [I] Connected.
Jan 27 17:47:52 (iftttie.context:50) [I] nest:structure:NFoW367Rt9Srr_hg0Pvi01Fb7R0JazU2pZp9To64fE8FExvo0FoJRA:away = 'home'
Jan 27 17:47:52 (iftttie.context:50) [I] nest:structure:NFoW367Rt9Srr_hg0Pvi01Fb7R0JazU2pZp9To64fE8FExvo0FoJRA:wwn_security_state = 'ok'
Jan 27 17:47:52 (iftttie.context:50) [I] nest:camera:q3x00MXx02yD67celwVrWGYhDcPZHDmmCn_-2slU1zZtYZY1MsHG6w:is_streaming = True
--
Jan 27 17:57:52 (iftttie.channels.nest:39) [W] Connection timeout.
Jan 27 17:57:52 (iftttie.channels.nest:31) [I] Connecting to the streaming API…
Jan 27 17:57:52 (iftttie.core:28) [I] Stopped channel Nest(token="c.Am…xoGd").
Jan 27 17:57:52 (asyncio.base_events:1591) [E] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb3f502f0>
```

**Comment by eigenein** [comment]
Seems to be stable at the moment.
